Messages:
  prefix: '&7[&3SmartGambling&7]'
  noPermission: '&cYou dont have permission to use this command!'
  reload: '%prefix% &aConfig successfully reloaded!'
  slotsAddCorrectUsage: '&cUse: /sg add <machine_type_name>'
  slotsAddStart: '%prefix% &aLeft click on the blocks you want to add!'
  selectBlockMessage: '%prefix% &a Block added at %s %s %s. '
  cancelButton: '&c&l[Cancel] '
  confirmButton: '&a&l[Confirm] '
  click: '&7click'
  canceledRoutine: '&cCanceled.'
  createdSlotMachine: '%prefix% &aMachine created successfully!'
  listSlots: '%prefix% &b&lMachines in your chunk : &8(use /sg list all to see all the machines in your world)'
  listAllSlots: '%prefix% &b&lMachines in your world :'
  listSlotsNoResult: '%prefix% &7No machines found in your chunk.'
  listSlotsResult: '%prefix% &bMachine &7(%s) &bat: &7%s&b. '
  teleportButton: '&a&l[TELEPORT] '
  removeButton: '&c&l[REMOVE] '
  idButton: '&9&l[COPY ID]'
  removedSlotMachines: '%prefix% &bRemoved &7%s &bmachines!'
  slotsRemoveCorrectUsage: '&cUse: /sg remove <all/chunkDataAddress>'
  chooseMoneyAmount: '%prefix% &aType the amount of money you want to bet:'
  invalidMoneyAmount: '%prefix% &cInvalid money amount! Please enter a number:'
  wonMoneyActionBar: '&aYou''ve won &a&l%s$&a!!'
  wonMoney: '%prefix% &aYou have won %s$! &7Your new balance: &7&l%s$'
  moneyExtracted: '&c&l-%s$ &cpaid. &7Your new balance: &7&l%s$'
  moneyReceived: '&a&l+%s$ &areceived. &7Your new balance: &7&l%s$'
  notEnoughMoneyActionBar: '&c&lYou do not have enough money!'
  machineAlreadyInUse: '&cThis machine is already being used.'
  timeLeft: '&a&lTime left: '
  jackpotWin: '&a!!! &6%s has won &6&l%s$ &6at the lottery!'
  jackpotWinOwn: '&a!!! &6You have won &6&l%s$ &6at the lottery!'
  jackpotReminder: '&7The lottery is starting in &7&l%s &7seconds. Use /jackpot to see the results live.'
  jackpotNextGame: '&7The lottery will start in &7&l%s&7.'
  jackpotAlreadyStarted: '&cThe lottery is currently running.'
  minutes: 'minutes'
  seconds: 'seconds'
  jackpotCommandDeny: '&cYou can not use this command here!'
  crashWin: '&6You have won &6&l%s$&6 at Crash. &7You stopped at %s before the crash at %s.'
  crashNextGame: '&7The game will start in &7&l%s&7.'
  crashAlreadyStarted: '&cThe game is currently running.'
  waitingForOpponent: '&cWaiting for opponent...'
  wonBlackJack: '&aYou have won at blackjack! Your value was %s, while your opponent''s was %s.'
  lostBlackJack: '&cYou have lost at blackjack! Your value was %s, while your opponent''s was %s.'
  drawBlackJack: '&7There was a draw! You both had the value %s.'
  drawBlackJackOver: '&7There was a draw! You both had values over 21.'
  opponentStopped: 'Stopped'
  opponentPlaying: 'Hasn''t stopped'
  blackjackAlreadyInUse: '&cThis table is occupied.'

helpMenu:
  - '&8-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-'
  - '&a&lSmartGambling v0.0.7 &r&7made by Arthed'
  - ''
  - '&9Use &r&9&l/sg reload &r&9to reload the config'
  - '&9Use &r&9&l/sg add <slot-type> &r&9to create a new physical slot machine'
  - '&9Use &r&9&l/sg list &r&9to list all the slot machines in your chunk'
  - '&9Use &r&9&l/sg remove <address> &r&9to remove a slot machine in your chunk'
  - '&9Use &r&9&l/sg remove all &r&9to remove all slots machines in your chunk'
  - '&8-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-'


Sounds:
  slotsWin:
    - BLOCK_NOTE_BLOCK_CHIME 2 1 0
    - BLOCK_NOTE_BLOCK_CHIME 2 1.2 10
    - BLOCK_NOTE_BLOCK_CHIME 2 1.4 10
  rareWin:
    - BLOCK_NOTE_BLOCK_BELL 2 0.8 0
    - BLOCK_NOTE_BLOCK_BELL 2 1 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.2 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.4 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.6 5
  jackpot:
    - UI_TOAST_CHALLENGE_COMPLETE 1 1 0
  lotteryWin:
    - UI_TOAST_CHALLENGE_COMPLETE 1 1 0
  crashWin:
    - BLOCK_NOTE_BLOCK_BELL 2 0.8 0
    - BLOCK_NOTE_BLOCK_BELL 2 1 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.2 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.4 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.6 5
  blackjackWin:
    - BLOCK_NOTE_BLOCK_BELL 2 0.8 0
    - BLOCK_NOTE_BLOCK_BELL 2 1 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.2 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.4 5
    - BLOCK_NOTE_BLOCK_BELL 2 1.6 5

Chair:
  material: STICK
  customModelData: 511
  Offset:
    x: 2
    y: -1
    z: 0